# Run with make -C /path/to/bsnes-plus/bsnes -f /path/to/this/file all.
# Uses the unmodified bsnes-plus accuracy/debugger CPU and PPU, no Qt required.
common := ../common
nall := $(common)/nall
include $(nall)/Makefile
snes := snes
profile := accuracy
objdir := obj/headless
cpp := g++ -std=gnu++11
flags := -O2 -I. -I$(common) -I$(snes) -Wno-switch -Wno-parentheses -include cstdint
compile = $(cpp) $(flags) -c $< -o $@
%.o: ; $(compile)
include snes/Makefile
all: $(snes_objects)
.PHONY: all
