#!/usr/bin/env python3
"""Pack the compiler's 10x14 tilemap into the SNES OBJ 16-tile row stride."""
import struct
import sys
from pathlib import Path
p=Path(sys.argv[1]); out=Path(sys.argv[2])
tiles=p.with_suffix('.4bpp').read_bytes()
pal=p.with_suffix('.pal').read_bytes()
words=struct.unpack('<140H',p.with_suffix('.map').read_bytes())
assert len(tiles)==4480 and len(pal)==32
packed=bytearray(14*16*32)
for y in range(14):
    for x in range(10):
        word=words[y*10+x]
        assert word < 140, 'bundle expects tile base/palette/priority zero'
        packed[(y*16+x)*32:(y*16+x+1)*32]=tiles[word*32:(word+1)*32]
# Reserve OBJ slots 32..66. Tile 64 starts at VRAM byte $c800.
oam=bytearray();hidden=bytearray()
for y in range(7):
    for x in range(5):
        tile=64+y*32+x*2
        entry=bytes((8+x*16,72+y*16,tile&255,0x30|(tile>>8)))
        oam+=entry
        hidden+=bytes((entry[0],240,entry[2],entry[3]))
# 35 large sprites (16x16); final unused sprite remains small/offscreen.
def asm(label,data):
    return label+'\n'+''.join('  .byt '+', '.join(f'${b:02x}' for b in data[i:i+16])+'\n' for i in range(0,len(data),16))
out.parent.mkdir(parents=True,exist_ok=True)
out.write_text('/* Generated by bundle_cover.py. Original STARFALL test art is CC0. */\n'+asm('fxos_cover_tiles',packed)+asm('fxos_cover_palette',pal)+asm('fxos_cover_oam',oam)+asm('fxos_cover_hidden',hidden)+asm('fxos_cover_oam_high',bytes([0xaa]*8+[0x2a])))
